// <auto-generated />

using Mango.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240612084757_addProjectApi")]
    partial class addProjectApi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Laptop",
                            Description = "A powerful and compact laptop",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Dell XPS 13",
                            Price = 0.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Laptop",
                            Description = "High-performance laptop with sleek design",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Apple MacBook Pro",
                            Price = 0.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Laptop",
                            Description = "Durable and reliable business laptop",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Lenovo ThinkPad X1",
                            Price = 0.0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Laptop",
                            Description = "Gaming laptop with high-end graphics",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Asus ROG Zephyrus",
                            Price = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
